version: "2"

linters:
  enable:
    - errcheck
    - govet
    - staticcheck
    - unused
    - ineffassign
    - gosec
    - errorlint
    - revive
    - gocritic
    - sloglint
  disable:
    - exhaustruct
    - varnamelen

linters-settings:
  revive:
    rules:
      # internal/runtime is an intentional name for the runtime abstraction
      # layer — not a collision with Go's stdlib "runtime" in practice.
      - name: redefines-builtin-id
        disabled: true

run:
  timeout: 2m
