// ABOUTME: Execute() entry point and root Cobra command wiring, including
// ABOUTME: exit-code mapping, bug-report lifecycle, and command group registration.
// Package cli defines the Cobra command tree for the yoloAI CLI.
package cli

import (
	"context"
	"errors"
	"fmt"
	"log/slog"
	"os"
	"time"

	"github.com/kstenerud/yoloai/internal/cli/cliutil"

	"github.com/kstenerud/yoloai/internal/config"
	"github.com/kstenerud/yoloai/internal/extension"
	"github.com/kstenerud/yoloai/internal/fileutil"
	"github.com/kstenerud/yoloai/internal/sandbox"
	"github.com/spf13/cobra"
)

// exitCodeSIGINT is the conventional exit code for SIGINT (128 + signal 2).
const exitCodeSIGINT = 130

// cliVersion, cliCommit, cliDate hold build-time info set in Execute and used
// by subcommands (e.g. sandbox bugreport) that need version info without
// threading it through every function call.
var cliVersion, cliCommit, cliDate string

// Execute runs the root command and returns the exit code.
func Execute(ctx context.Context, version, commit, date string) (exitCode int) {
	cliVersion, cliCommit, cliDate = version, commit, date
	rootCmd := newRootCmd(version, commit, date)

	// Track which command was active when the error occurred so we can
	// show a context-aware help hint (e.g. "Run 'yoloai system prune -h' for help").
	var activeCmd *cobra.Command
	rootCmd.PersistentPreRunE = func(cmd *cobra.Command, _ []string) error {
		activeCmd = cmd
		cliutil.InitLogger(cmd)
		return initBugReport(cmd, version, commit, date)
	}
	prev := rootCmd.FlagErrorFunc()
	rootCmd.SetFlagErrorFunc(func(cmd *cobra.Command, err error) error {
		activeCmd = cmd
		if prev != nil {
			return prev(cmd, err)
		}
		return err
	})

	// Deferred bug report finalizer: writes sections 13-14 and renames temp → final.
	var runErr error
	var panicked bool
	defer func() {
		r := recover()
		if r != nil {
			panicked = true
		}
		finalizeBugReport(exitCode, runErr, panicked)
		if panicked {
			panic(r)
		}
	}()

	runErr = rootCmd.ExecuteContext(ctx)
	if runErr == nil {
		return 0
	}

	if errors.Is(runErr, context.Canceled) {
		return exitCodeSIGINT
	}

	printRunError(runErr, rootCmd, activeCmd)
	return errorExitCode(runErr)
}

// printRunError writes the run error to stderr in JSON or human-readable form.
func printRunError(runErr error, rootCmd *cobra.Command, activeCmd *cobra.Command) {
	if jsonFlag, _ := rootCmd.PersistentFlags().GetBool("json"); jsonFlag {
		cliutil.WriteJSONError(os.Stderr, runErr)
		return
	}
	fmt.Fprintf(os.Stderr, "yoloai: %s\n", runErr) //nolint:errcheck // best-effort stderr write

	// If this is a raw ENOSPC that wasn't wrapped at the call site, the
	// user just saw the underlying error without the recovery hint that
	// *DiskSpaceError carries. Append the same hint here so the message
	// is actionable regardless of whether the runtime layer wrapped.
	if _, alreadyWrapped := errors.AsType[*sandbox.DiskSpaceError](runErr); !alreadyWrapped && sandbox.IsDiskSpaceError(runErr) {
		fmt.Fprintln(os.Stderr, "Free space and retry:")                                                                //nolint:errcheck
		fmt.Fprintln(os.Stderr, "  yoloai system disk             # show what yoloai is using")                         //nolint:errcheck
		fmt.Fprintln(os.Stderr, "  yoloai system prune --cache    # reclaim backend image cache (forces base rebuild)") //nolint:errcheck
	}

	if activeCmd != nil {
		fmt.Fprintf(os.Stderr, "Run '%s -h' for help\n", activeCmd.CommandPath()) //nolint:errcheck // best-effort stderr write
	}
}

// initBugReport handles --bugreport flag setup during PersistentPreRunE.
func initBugReport(cmd *cobra.Command, version, commit, date string) error {
	brType, _ := cmd.Root().PersistentFlags().GetString("bugreport")
	if brType == "" {
		return nil
	}
	if brType != "safe" && brType != "unsafe" {
		return sandbox.NewUsageError("--bugreport: must be safe or unsafe")
	}
	name, err := bugReportFilename(time.Now().UTC())
	if err != nil {
		return fmt.Errorf("--bugreport: %w", err)
	}
	cliutil.BugReportFinalName = name
	cliutil.BugReportType = brType
	f, err := fileutil.OpenFile(name+".tmp", os.O_CREATE|os.O_EXCL|os.O_WRONLY, 0600) //nolint:gosec // G304: filename generated by bugReportFilename
	if err != nil {
		return fmt.Errorf("--bugreport: open temp file: %w", err)
	}
	cliutil.BugReportFile = f
	writeBugReportHeader(f, version, commit, date, brType)
	writeBugReportCommandInvocation(f, brType)
	writeBugReportSystem(f)
	writeBugReportBackends(cmd.Context(), f)
	writeBugReportConfig(f, brType)
	cliutil.AddLogSink(&cliutil.LiveLogBuf, slog.LevelDebug)
	return nil
}

// finalizeBugReport writes the bug report footer and renames the temp file if one is open.
func finalizeBugReport(exitCode int, runErr error, panicked bool) {
	if cliutil.BugReportFile == nil {
		return
	}
	code := exitCode
	if panicked {
		code = 1
	}
	if cliutil.BugReportSandboxName != "" {
		writeBugReportSandboxSectionsForFlag(cliutil.BugReportFile, cliutil.BugReportSandboxName, cliutil.BugReportType)
	}
	writeBugReportLiveLog(cliutil.BugReportFile, cliutil.LiveLogBuf.Bytes(), cliutil.BugReportType)
	writeBugReportExit(cliutil.BugReportFile, code, runErr, panicked)
	_ = cliutil.BugReportFile.Close()
	_ = os.Rename(cliutil.BugReportFinalName+".tmp", cliutil.BugReportFinalName)
	if info, err := os.Stat(cliutil.BugReportFinalName); err == nil && info.Size() > 65536 {
		fmt.Fprintf(os.Stderr, "Warning: report exceeds GitHub's issue body limit (65,536 characters).\n")  //nolint:errcheck
		fmt.Fprintf(os.Stderr, "Upload as a Gist instead: gh gist create %s\n", cliutil.BugReportFinalName) //nolint:errcheck
	}
	fmt.Fprintf(os.Stderr, "Bug report written: %s\n", cliutil.BugReportFinalName) //nolint:errcheck
}

// errorExitCode maps an error to the appropriate exit code.
func errorExitCode(err error) int {
	if exitErr, ok := errors.AsType[*extension.ExitError](err); ok {
		return exitErr.Code
	}

	if _, ok := errors.AsType[*sandbox.UsageError](err); ok {
		return 2
	}

	if _, ok := errors.AsType[*sandbox.ConfigError](err); ok {
		return 3
	}

	if _, ok := errors.AsType[*sandbox.ActiveWorkError](err); ok {
		return 4
	}

	if _, ok := errors.AsType[*sandbox.DependencyError](err); ok {
		return 5
	}

	if _, ok := errors.AsType[*sandbox.PlatformError](err); ok {
		return 6
	}

	if _, ok := errors.AsType[*sandbox.AuthError](err); ok {
		return 7
	}

	if _, ok := errors.AsType[*sandbox.PermissionError](err); ok {
		return 8
	}

	if _, ok := errors.AsType[*sandbox.SandboxLockedError](err); ok {
		return 9
	}

	// DiskSpaceError catches both explicitly-wrapped sites (via
	// AsDiskSpaceError) and unwrapped ENOSPC errors that flowed up
	// from runtimes without typing — IsDiskSpaceError sniffs both
	// syscall.ENOSPC and the common string forms.
	if _, ok := errors.AsType[*sandbox.DiskSpaceError](err); ok {
		return 10
	}
	if sandbox.IsDiskSpaceError(err) {
		return 10
	}

	return 1
}

// newRootCmd creates the root Cobra command with all subcommands registered.
func newRootCmd(version, commit, date string) *cobra.Command {
	rootCmd := &cobra.Command{
		Use:   "yoloai",
		Short: "Sandboxed AI coding agent runner",
		Long: `Run AI coding agents in full-auto mode, safely. Agents run with
safety checks disabled inside disposable sandboxes — they work fast
and unattended while your originals stay protected. When done, review the
diff and apply what you want to keep.`,
		SilenceErrors: true,
		SilenceUsage:  true,
		Run: func(cmd *cobra.Command, _ []string) {
			w := cmd.OutOrStdout()
			fmt.Fprintln(w, "yoloai — sandboxed AI coding agent runner") //nolint:errcheck // best-effort stdout write
			fmt.Fprintln(w)                                              //nolint:errcheck // best-effort stdout write
			fmt.Fprintln(w, "Run 'yoloai help' to get started")          //nolint:errcheck // best-effort stdout write
			fmt.Fprintln(w, "Run 'yoloai -h' for command-line options")  //nolint:errcheck // best-effort stdout write
		},
	}

	// Disable Cobra's built-in help subcommand; we register our own.
	// GroupID prevents an empty "Additional Commands:" header in -h output.
	rootCmd.SetHelpCommand(&cobra.Command{Hidden: true, Use: "no-help", GroupID: cliutil.GroupAdmin})

	// Register --help/-h as persistent so it appears under "Global Flags"
	// on every command. Cobra's InitDefaultHelpFlag skips adding a local
	// --help when one already exists via persistent inheritance.
	rootCmd.PersistentFlags().BoolP("help", "h", false, "Help for this command")

	rootCmd.PersistentFlags().CountP("verbose", "v", "Increase output verbosity (-v for debug, -vv reserved)")
	rootCmd.PersistentFlags().CountP("quiet", "q", "Suppress non-essential output (-q for error only)")
	rootCmd.PersistentFlags().Bool("json", false, "Output as JSON (machine-readable)")
	rootCmd.PersistentFlags().Bool("debug", false, "Enable debug-level entries in cli.jsonl")
	rootCmd.PersistentFlags().String("bugreport", "", "Write bug report (safe|unsafe)")
	rootCmd.PersistentFlags().String("data-dir", "", "Override the yoloai data directory (default: $HOME/.yoloai/). HTTP/MCP/daemon/test embedders pass explicit paths; see development-principles.md §12.")

	// Persistent pre-run: when --data-dir is supplied, record it as the
	// process-wide rootLayout. Otherwise leave rootLayout empty so
	// cliutil.Layout() resolves $HOME/.yoloai/ freshly on each call (important
	// for tests that t.Setenv("HOME", ...) between cases). The HOME read
	// goes through homeBasedDataDir(), the W-L10-allowlisted site.
	prevPersistentPreRunE := rootCmd.PersistentPreRunE
	rootCmd.PersistentPreRunE = func(cmd *cobra.Command, args []string) error {
		if dataDir, _ := cmd.Flags().GetString("data-dir"); dataDir != "" {
			cliutil.SetRootLayout(config.NewLayout(dataDir))
		}
		if prevPersistentPreRunE != nil {
			return prevPersistentPreRunE(cmd, args)
		}
		return nil
	}

	registerCommands(rootCmd, version, commit, date)

	return rootCmd
}
