// Package cli defines the Cobra command tree for the yoloAI CLI.
package cli

import (
	"context"
	"errors"
	"fmt"
	"log/slog"
	"os"
	"time"

	"github.com/kstenerud/yoloai/config"
	"github.com/kstenerud/yoloai/extension"
	"github.com/kstenerud/yoloai/sandbox"
	"github.com/spf13/cobra"
)

// exitCodeSIGINT is the conventional exit code for SIGINT (128 + signal 2).
const exitCodeSIGINT = 130

// cliVersion, cliCommit, cliDate hold build-time info set in Execute and used
// by subcommands (e.g. sandbox bugreport) that need version info without
// threading it through every function call.
var cliVersion, cliCommit, cliDate string

// Execute runs the root command and returns the exit code.
func Execute(ctx context.Context, version, commit, date string) (exitCode int) {
	cliVersion, cliCommit, cliDate = version, commit, date
	rootCmd := newRootCmd(version, commit, date)

	// Track which command was active when the error occurred so we can
	// show a context-aware help hint (e.g. "Run 'yoloai system prune -h' for help").
	var activeCmd *cobra.Command
	rootCmd.PersistentPreRunE = func(cmd *cobra.Command, _ []string) error {
		activeCmd = cmd
		initLogger(cmd)

		// --bugreport: validate, open temp file, write sections 1-5, enable debug sink.
		brType, _ := cmd.Root().PersistentFlags().GetString("bugreport")
		if brType != "" {
			if brType != "safe" && brType != "unsafe" {
				return sandbox.NewUsageError("--bugreport: must be safe or unsafe")
			}
			name, err := bugReportFilename(time.Now().UTC())
			if err != nil {
				return fmt.Errorf("--bugreport: %w", err)
			}
			bugReportFinalName = name
			bugReportType = brType
			f, err := os.OpenFile(name+".tmp", os.O_CREATE|os.O_EXCL|os.O_WRONLY, 0600) //nolint:gosec // G304: filename generated by bugReportFilename
			if err != nil {
				return fmt.Errorf("--bugreport: open temp file: %w", err)
			}
			bugReportFile = f
			writeBugReportHeader(f, version, commit, date, brType)
			writeBugReportCommandInvocation(f, brType)
			writeBugReportSystem(f)
			writeBugReportBackends(cmd.Context(), f)
			writeBugReportConfig(f, brType)
			AddLogSink(&liveLogBuf, slog.LevelDebug)
		}
		return nil
	}
	prev := rootCmd.FlagErrorFunc()
	rootCmd.SetFlagErrorFunc(func(cmd *cobra.Command, err error) error {
		activeCmd = cmd
		if prev != nil {
			return prev(cmd, err)
		}
		return err
	})

	// Deferred bug report finalizer: writes sections 13-14 and renames temp → final.
	var runErr error
	var panicked bool
	defer func() {
		r := recover()
		if r != nil {
			panicked = true
		}
		if bugReportFile != nil {
			code := exitCode
			if panicked {
				code = 1
			}
			if bugReportSandboxName != "" {
				writeBugReportSandboxSectionsForFlag(bugReportFile, bugReportSandboxName, bugReportType)
			}
			writeBugReportLiveLog(bugReportFile, liveLogBuf.Bytes(), bugReportType)
			writeBugReportExit(bugReportFile, code, runErr, panicked)
			_ = bugReportFile.Close()
			_ = os.Rename(bugReportFinalName+".tmp", bugReportFinalName)
			if info, err := os.Stat(bugReportFinalName); err == nil && info.Size() > 65536 {
				fmt.Fprintf(os.Stderr, "Warning: report exceeds GitHub's issue body limit (65,536 characters).\n") //nolint:errcheck
				fmt.Fprintf(os.Stderr, "Upload as a Gist instead: gh gist create %s\n", bugReportFinalName)        //nolint:errcheck
			}
			fmt.Fprintf(os.Stderr, "Bug report written: %s\n", bugReportFinalName) //nolint:errcheck
		}
		if panicked {
			panic(r)
		}
	}()

	runErr = rootCmd.ExecuteContext(ctx)
	if runErr == nil {
		return 0
	}

	if errors.Is(runErr, context.Canceled) {
		return exitCodeSIGINT
	}

	// In JSON mode, errors go to stderr as JSON
	if jsonFlag, _ := rootCmd.PersistentFlags().GetBool("json"); jsonFlag {
		writeJSONError(os.Stderr, runErr)
	} else {
		fmt.Fprintf(os.Stderr, "yoloai: %s\n", runErr) //nolint:errcheck // best-effort stderr write
		if activeCmd != nil {
			fmt.Fprintf(os.Stderr, "Run '%s -h' for help\n", activeCmd.CommandPath()) //nolint:errcheck // best-effort stderr write
		}
	}

	var exitErr *extension.ExitError
	if errors.As(runErr, &exitErr) {
		return exitErr.Code
	}

	var usageErr *sandbox.UsageError
	if errors.As(runErr, &usageErr) {
		return 2
	}

	var configErr *sandbox.ConfigError
	if errors.As(runErr, &configErr) {
		return 3
	}

	var activeWorkErr *config.ActiveWorkError
	if errors.As(runErr, &activeWorkErr) {
		return 4
	}

	var depErr *config.DependencyError
	if errors.As(runErr, &depErr) {
		return 5
	}

	var platErr *config.PlatformError
	if errors.As(runErr, &platErr) {
		return 6
	}

	var authErr *config.AuthError
	if errors.As(runErr, &authErr) {
		return 7
	}

	var permErr *config.PermissionError
	if errors.As(runErr, &permErr) {
		return 8
	}

	return 1
}

// newRootCmd creates the root Cobra command with all subcommands registered.
func newRootCmd(version, commit, date string) *cobra.Command {
	rootCmd := &cobra.Command{
		Use:   "yoloai",
		Short: "Sandboxed AI coding agent runner",
		Long: `Run AI coding agents in full-auto mode, safely. Agents run with
safety checks disabled inside disposable sandboxes — they work fast
and unattended while your originals stay protected. When done, review the
diff and apply what you want to keep.`,
		SilenceErrors: true,
		SilenceUsage:  true,
		Run: func(cmd *cobra.Command, _ []string) {
			w := cmd.OutOrStdout()
			fmt.Fprintln(w, "yoloai — sandboxed AI coding agent runner") //nolint:errcheck // best-effort stdout write
			fmt.Fprintln(w)                                              //nolint:errcheck // best-effort stdout write
			fmt.Fprintln(w, "Run 'yoloai help' to get started")          //nolint:errcheck // best-effort stdout write
			fmt.Fprintln(w, "Run 'yoloai -h' for command-line options")  //nolint:errcheck // best-effort stdout write
		},
	}

	// Disable Cobra's built-in help subcommand; we register our own.
	// GroupID prevents an empty "Additional Commands:" header in -h output.
	rootCmd.SetHelpCommand(&cobra.Command{Hidden: true, Use: "no-help", GroupID: groupAdmin})

	// Register --help/-h as persistent so it appears under "Global Flags"
	// on every command. Cobra's InitDefaultHelpFlag skips adding a local
	// --help when one already exists via persistent inheritance.
	rootCmd.PersistentFlags().BoolP("help", "h", false, "Help for this command")

	rootCmd.PersistentFlags().CountP("verbose", "v", "Increase output verbosity (-v for debug, -vv reserved)")
	rootCmd.PersistentFlags().CountP("quiet", "q", "Suppress non-essential output (-q for error only)")
	rootCmd.PersistentFlags().Bool("json", false, "Output as JSON (machine-readable)")
	rootCmd.PersistentFlags().Bool("debug", false, "Enable debug-level entries in cli.jsonl")
	rootCmd.PersistentFlags().String("bugreport", "", "Write bug report (safe|unsafe)")

	registerCommands(rootCmd, version, commit, date)

	return rootCmd
}
